## Classifying Passwords Strength With Machine Learning in Python

In [1]:
# EDA Packages
import pandas as pd
import numpy as np
import random


# Machine Learning Packages
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [2]:
# Load Passwordlist
# Credits Faizan
#pswd_data = pd.read_csv("passwordsdata.csv",error_bad_lines=False)
pswd_data = pd.read_csv("cleanpasswordlist.csv")

In [3]:
pswd_data.head()

Unnamed: 0     password  strength
0           0     kzde5577         1
1           1     kino3434         1
2           2    visi7k1yr         1
3           3     megzy123         1
4           4  lamborghin1         1

In [4]:
pswd = np.array(pswd_data)

In [5]:
# Shuffle data 
random.shuffle(pswd)

In [6]:
# Grouping our data into features and labels
# y = labels
ylabels  = [s[2] for s in pswd]
allpasswords = [s[1] for s in pswd]

In [7]:
ylabels
len(ylabels)

669425

In [8]:
len(allpasswords)

669425

### Data Vectorization Using TfidVectorizer
#### Create A tokenizer
 + Use either the entire password
 + Use each character

In [9]:
def makeTokens(f):
    tokens = []
    for i in f:
        tokens.append(i)
    return tokens

In [10]:
# Using Default Tokenizer
#vectorizer = TfidfVectorizer()

# Using Custom Tokenizer
vectorizer = TfidfVectorizer(tokenizer=makeTokens)

In [11]:
# Store vectors into X variable as Our X allpasswords
X = vectorizer.fit_transform(allpasswords)

##### Splitting Data Into Train and Test at 80/20

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, ylabels, test_size=0.2, random_state=42)	

In [13]:
# Model Building
#using logistic regression
# Multi_class for fast algorithm
logit = LogisticRegression(penalty='l2',multi_class='ovr')	
logit.fit(X_train, y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

#### Accuracy of Our Model

In [14]:
print("Accuracy :",logit.score(X_test, y_test))

Accuracy : 0.811263397692


#### Predicting With Our Model

In [15]:
X_predict = ['password',
             'pYthon'
             'faizanahmad',
             'password##',
             'ajd1348#28t**',
             'ffffffffff',
             'kuiqwasdi',
             '123456',
             'abcdef']

X_predict = vectorizer.transform(X_predict)
y_Predict = logit.predict(X_predict)
print(y_Predict)

[0 2 0 2 0 1 1 0]


In [16]:
# http://www.passwordmeter.com/
# https://password.kaspersky.com/

New_predict = ["1qaz2wsx",
"306187mn",
"rados1#@1$#@$@$#@$",
"newyork911",
"abc123",
"taqiyudin100587",
"wjr5443",
"nana0428"]

New_predict = vectorizer.transform(New_predict)
y_Predict = logit.predict(New_predict)
print(y_Predict)

[1 1 2 1 1 1 1 1]


In [17]:
# Using Default Tokenizer
vectorizer = TfidfVectorizer()
# Store vectors into X variable as Our X allpasswords
X1 = vectorizer.fit_transform(allpasswords)


In [18]:
X_train, X_test, y_train, y_test = train_test_split(X1, ylabels, test_size=0.2, random_state=42)	

In [19]:
# Model Building
#using logistic regression
# Multi_class for fast algorithm
logit = LogisticRegression(penalty='l2',multi_class='ovr')	
logit.fit(X_train, y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [20]:
print("Accuracy :",logit.score(X_test, y_test))

Accuracy : 0.776360309221


In [ ]:
# Using th

In [21]:
X_predict1 = ['password',
             'pYthonqwas'
             'faizanahmad',
             'password##',
             'ajd1348#28t**',
             'ffffffffff',
             'kuiqwasdi',
             '123456',
             'abcdef']

X_predict1 = vectorizer.transform(X_predict1)
y_Predict1 = logit.predict(X_predict1)
print(y_Predict1)

[1 1 1 1 1 1 1 1]


In [22]:
New_predict2 = ["1qaz2wsx",
"306187mn",
"rados1",
"newyork911",
"abc123",
"taqiyudin100587",
"wjr5443",
"nana0428"]

New_predict2 = vectorizer.transform(New_predict2)
y_Predict2 = logit.predict(New_predict2)
print(y_Predict2)

[1 1 1 1 1 1 1 1]


In [ ]:
#Thanks 
#J-Secur1ty
#Jesus Saves @ JCharisTech